name: LoadX
main: xyz.derkades.loadx.Main
version: 2.0.0
author: Derkades
description: Plugin for automatically generating chunks

commands:
  generate:
    aliases: [load, loadchunks, generatechunks, autogenerate, autoload, loadx]
    description: Automatically teleports the player to generate chunks.
    usage: |
      /generate <blocks>
      
      Blocks -  The amount of blocks in x and z direction you want to generate, for example:
      blocks = 2000 will generate to x=-2000, x=2000, z=-2000, z=2000